# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
trigger:
  branches:
    include:
    - master
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/luis/

pr:
  branches:
    include:
    - master
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - common/Perf/
    - common/PerfStressShared/
    - common/Stress/
    - sdk/luis/

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: luis
    ArtifactName: packages
    Artifacts:
    - name: Azure.AI.Luis
      safeName: AzureAILuis
